config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'
  resources :songs do
    resources :likes, only: [:create]
    member do
      delete :likes, to: 'likes#destroy'
    end
  end

  resources :users, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  get    '/login',  to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user

  has_many :likes
  has_many :liked_by, :through => :likes, :source => :user


  def self.search(query)
    wildcarded_query = "%#{query}%"
    where(
      "artist ILIKE :artist OR title ILIKE :title",
      artist: wildcarded_query,
      title: wildcarded_query
    )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :songs
  has_many :likes
  has_many :liked_songs, :through => :likes, :source => :song

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def likes?(song)
    !(self.likes.find_by song: song).nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: "Please create an account or login" unless current_user
  end

  def current_user?(user)
    user == current_user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @song = Song.find(params[:song_id])
    @user = current_user
    @like = Like.create(user_id: @user.id, song_id: @song.id)
    #current_user.likes << @song.song_id
    redirect_to song_path(@song)
  end

  def destroy
    @song = Song.find(params[:id])
    @likes = Like.where(
      'user_id = :user_id AND song_id = :song_id',
      user_id: current_user.id,
      song_id: @song.id
    )
    @likes.destroy_all
    redirect_to song_path(@song)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now.alert = 'Invalid login credentials'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Successfully Logged Out'
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :authorize, only: [:edit, :new, :create, :update, :destroy, :logout]
  before_action :correct_user, only: [:edit, :update, :destroy, :logout]
  before_action :check_if_song_belongs_to_current_user, only: [:edit, :update, :destroy]

  def index
    @current_month = Time.now.strftime("%B")
    most_liked = Song.joins(:likes).group(:song_id).order('count_song_id DESC').limit(4).count(:song_id).keys
    @top_songs = Song.find(most_liked)
    @songs = Song.all
    if params[:search]
      @songs = Song.search(params[:search]).order("created_at DESC")
    else
      @songs = Song.all
      flash[:notice] = "No results match search"
    end
  end


  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      current_user.songs << @song
      flash[:notice] = "Added Song"
      redirect_to song_path(@song.id)
    else
      render 'new'
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    @song.update(song_params)
    if @song.save
      flash[:notice] = "Updated Song"
      redirect_to song_path
    else
      render 'show'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @likes = Like.where('song_id = :song_id', song_id: @song.id)
    @likes.destroy_all
    @song.destroy
    redirect_to user_path(current_user)
  end

  private
  def song_params
    params.require(:song).permit(:artist, :title, :lyric, :user_id)
  end

  def correct_user
    @User = current_user
    redirect_to(root_path) unless current_user?(@User)
  end

  def check_if_song_belongs_to_current_user
    @User = current_user
    @song = Song.find(params[:id])
    if @song[:user_id] == @User.id
      true
    else
      false
      redirect_to song_path(@song.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show, :edit, :update, :destroy, :logout]
  before_action :correct_user, only: [:show, :edit, :update, :destroy, :logout]

  def index
    @songs = Song.where(user_id: current_user.id)
  end

  def likes
    @user = User.find(params[:id])
    @likes = @user.likes
    render 'show_likes'
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up"
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @uploaded_songs = Song.where(user_id: current_user.id)
    @user = User.find(params[:id])
    @songs_array = @user.likes.pluck(:song_id)
    @songs = @songs_array.reverse
    @songs_list = Song.where(id: @songs).reverse
  end

  def liked_songs
    @user = current_user
    @songs_array = @user.likes.pluck(:song_id)
    @songs = @songs_array.reverse
    @songs_list = Song.where(id: @songs).select(['artist', 'title']).reverse
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "Updated Profile"
      redirect_to songs_path
    else
      redirect_to edit_user_path
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Museo-Lyrics
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"}
    %link{:href => "https://fonts.googleapis.com/css?family=Fjalla+One", :rel => "stylesheet", :type => "text/css"}/
  %body{:style => "background-color: indigo;"}
    %br/
    .container
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            %a.navbar-brand{:href => "/"}
              .logo
                %p.logo_text Museo-Lyrics
            %br/
          %ul.nav.navbar-nav.navbar-brand
            - if !current_user
              %li{:style => "font-size: 70%; display: inline-block; font-family: 'Fjalla One', sans-serif;"}
                %a{:href => "/"} Home
              %li{:style => "font-size: 70%; display: inline-block; font-family: 'Fjalla One', sans-serif;"}
                %a{:href => "/login"} Login
              %li{:style => "font-size: 70%; display: inline-block; font-family: 'Fjalla One', sans-serif;"}
                %a{:href => "/users/new"} Sign Up
            - else
              %li{:style => "font-size: 70%; display: inline-block; font-family: 'Fjalla One', sans-serif;"}
                %a{:href => "/users/#{current_user.id}"} Songs
              %li{:style => "font-size: 70%; display: inline-block; font-family: 'Fjalla One', sans-serif;"}
                %a{:href => "/songs/new"} Add Song
              %li{:style => "font-size: 70%; display: inline-block; font-family: 'Fjalla One', sans-serif;"}
                %a{:href => "/users/#{current_user.id}/edit"} Edit Profile
              %li{:style => "font-size: 70%; display: inline-block; font-family: 'Fjalla One', sans-serif;"}= link_to "Logout", "/logout", method: :delete
      = yield

app/views/songs/edit.html.haml
#links
  = link_to "Delete Song", song_path, method: :destroy, :class => "delete_song", data: {confirm: "Delete this song?"}
%strong
  %u{:style => "color: ghostwhite;"}
    %h1.add_song Edit Song
= form_for @song do |f|
  - if @song.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @song.errors.full_messages
          %li= message
  #container
    .field
      .row
        = f.label :artist
      .text_row
        = f.text_field :artist
      %br/
    .field
      .row
        = f.label :title
      .text_row
        = f.text_field :title
      %br/
    .field
      .row
        = f.label :lyrics
      .text_row
        = f.text_area :lyric, :rows => 20, :cols => 70
    .actions= f.submit

app/views/songs/index.html.haml
%section.form-container.align-center
  = bootstrap_form_tag song: songs_path, method: :get do |f|
    = f.text_field :search, placeholder: "Search songs", |
    hide_label: true, value: params[:search],          |
    autofocus: true, wrapper: {class: "float-left"}    |
  = link_to "Clear", songs_path, class: "btn btn-primary"
  %br{:style => "clear: both;"}/
%br/
%br/
- if params[:search]
  #songs_container{:style => "display: block;\n  position: relative;\n  top: 10px;\n  margin: 0px auto;\n  border: solid silver 4px;\n  border-radius: 4px;\n  width: auto;\n  height: auto;\n  padding: 15px;\n  text-align: center;\n  background-color: ghostwhite;\n  opacity: 0.25%;"}
    %h1{:style => "color: black; font-family: 'Fjalla One', sans-serif;"}
      %u
        Search Results for "#{params[:search]}"
    - @songs.reverse.each do |s|
      %a{:href => "/songs/#{s.id}", :style => "color: black; font-family: 'Fjalla One', sans-serif;"}
        = s.artist
        "#{s.title}"
        %span
          - if s.likes.count > 0
            - if s.likes.count == 1
              = s.likes.count
              Like
            - else
              = s.likes.count
              Likes
        %br/
        %br/
- else
  #top_songs
    %h1{:style => "color: black; font-family: 'Fjalla One', sans-serif;"}
      %u
        Top 4 of #{@current_month}
    #artists{:style => "border-radius: 0px;}
      - if @top_songs
        - @top_songs.each do |a|
          %a{:href => "/songs/#{a.id}", :style => "color: black; font-family: 'Fjalla One', sans-serif;"}
            = a.artist
            "#{a.title}"
            %span
              - if a.likes.count > 0
                - if a.likes.count == 1
                  = a.likes.count
                  Like
                - else
                  = a.likes.count
                  Likes
          %br/
          %br/
    #recent_songs
      %h1{:style => "color: black; font-family: 'Fjalla One', sans-serif;"}
        %u Recent Songs
      - @songs.last(10).reverse.each do |s|
        %a#resongs{:href => "/songs/#{s.id}", :style => "color: black; font-family: 'Fjalla One', sans-serif;"}
          = s.artist
          "#{s.title}"
          %span
            - if s.likes.count > 0
              - if s.likes.count == 1
                = s.likes.count
                Like
              - else
                = s.likes.count
                Likes
          %br/
          %br/

app/views/songs/new.html.haml
= form_for @song do |f|
  - if @song.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @song.errors.full_messages
          %li= message
  #add_new_song
    %strong
      %u{:style => "color: lightgreen;"}
        %h1.add_song Add Song
    %br/
    #container
      .field
        .row
          = f.label :artist
        .text_row
          = f.text_field :artist, :class => "artist_field"
        %br/
      .field
        .row
          = f.label :title
        .text_row
          = f.text_field :title, :class => "title_field"
        %br/
      .field
        .row
          = f.label :lyrics
        .text_row
          = f.text_area :lyric, :rows => 20, :cols => 70, :class => "lyric_field"
      .actions= f.submit
    = link_to "Cancel", "/"

app/views/songs/show.html.haml
.container-fluid.song-color
  .row
    #show_likes.col-md-2.col-md-offset-2
      %h3
        = @song.likes.count
        = "Like".pluralize(@song.likes.count)
      - if current_user
        - if current_user.likes?(@song)
          %h4{:style => "color: lightgreen;"}= button_to "UNLIKE", likes_song_path(@song), method: :delete
        - else
          %h4{:style => "color: lightgreen;"}= button_to "LIKE", song_likes_path(@song)
      - if current_user && @song.user == current_user
        %p
          = link_to "Edit", edit_song_path, class: "link_to_edit"
          |
          \#{link_to( "Destroy", song_path, method: :delete, data: {confirm: "Are you sure?"}, class: "link_to_destroy" )}
    #show_links.col-md-4
      %p
        Artist: #{@song.artist}
      %br/
      %p
        Title: #{@song.title}
      %br/
      %br/
      .show_lyric
        %p
          Lyrics:
          %br/
          %br/
        %pre= @song.lyric

app/views/users/edit.html.haml
#edit_user
  %h1{:style => "color: lightgreen;"}
    %u Update Your Profile
  %br/
  = form_for @user do |f|
    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @user.errors.full_messages
            %li= message
    .field
      = f.label :name
      = f.text_field :name, :class => "name_input_edit_user"
    .field
      = f.label :email
      = f.text_field :email, :class => "email_input_edit_user"
    .field
      = f.label :password
      = f.password_field :password, :class => "password_input_edit_user"
    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation, :class => "password_confirm_input_edit_user"
    .actions= f.submit

app/views/users/index.html.haml
%br/
%br/
%br/
%h1{:style => "display: block;position:relative;margin: 0px auto; text-align: center; padding-bottom: 5px;"}
  %u Uploaded Songs
%br/
#uploaded_songs
  - @songs.reverse.each do |l|
    %a{:href => "/songs/#{l.id}", :style => "color: black"}
      = l.artist
      \- "#{l.title}" #{l.likes.count}
      - if l.likes.count == 1
        Like
      - else
        Likes
    %br/

app/views/users/new.html.haml
#add_new_user
  %h1{:style => "color: lightgreen; margin: 0px auto;"}
    %u Sign Up
  %br/
  = form_for @user do |f|
    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @user.errors.full_messages
            %li= message
    .field
      = f.label :name
      = f.text_field :name, :class => "name_input_new_user"
    .field
      = f.label :email
      = f.text_field :email, :class => "email_input_new_user"
    .field
      = f.label :password
      = f.password_field :password, :class => "password_input_new_user"
    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation, :class => "password_confirmation_input_new_user"
    %br/
    .actions= f.submit

app/views/users/show.html.haml
%br/
%br/
%br/
%h1{:style => "display: block; position:relative; margin: 0px auto; text-align: center; padding-bottom: 5px;"}
  %u Uploaded Songs
%br/
#uploaded_songs
  - @uploaded_songs.reverse.each do |l|
    %a{:href => "/songs/#{l.id}", :style => "color: black"}
      = l.artist
      \- "#{l.title}" #{l.likes.count}
      - if l.likes.count == 1
        Like
      - else
        Likes
    %br/
%br/
%br/
%br/
%h1{:style => "display: block; position:relative; margin: 0px auto; text-align: center; padding-bottom: 5px;"}
  %u Liked Songs
%br/
#liked_songs
  - @songs_list.reverse.each do |l|
    %a{:href => "/songs/#{l.id}", :style => "color: black"}
      = l.artist
      \- "#{l.title}" #{l.likes.count}
      - if l.likes.count == 1
        Like
      - else
        Likes
    %br/

app/views/users/show_likes.html.erb
<% songs.where(Like.user_id: = songs.user_id).each do |l| %>

  <p><%= l.artist %> - "<%= l.title %>" %></p><br/><br/>

<% end %>